# Classification Agorithms

## **Loan Eligibility Prediction Model**

### Project Scope:

Loans form an integral part of banking operations. However, not all loans are returned and hence it is important for a bank to closely moniter its loan applications. This case study is an analysis of the German Credit data. It contains details of 614 loan applicants with 13 attributes and the classification whether an applicant was granted loan or denied loan.

**Your role:** Using the available dataset, train a classification model to predict whether an applicant should be given loan.

**Goal:** Build a model to predict loan eligiblity with an average acuracy of more than 76%

**Specifics:**

* Machine Learning task: Classification model
* Target variable: Loan_Approved
* Input variables: Refer to data dictionary below
* Success Criteria: Accuracy of 76% and above


## Data Dictionary:

* **Loan_ID:** Applicant ID
* **Gender:** Gender of the applicant Male/Female
* **Married:** Marital status of the applicant
* **Dependents:** Number of dependants the applicant has
* **Education:** Highest level of education
* **Self_Employed:** Whether self-employed Yes/No
* **ApplicantIncome:** Income of the applicant per month
* **CoapplicantIncome:** Income of the co-applicant per month
* **LoanAmount:** Loan amount requested in *1000 dollars
* **Loan_Amount_Term:** Term of the loan in months
* **Credit_History:** Whether applicant has a credit history
* **Property_Area:** Current property location
* **Loan_Approved:** Loan approved yes/no

## **Data Analysis and Data Prep**

### Loading all the necessary packages

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

### Reading the data

In [5]:
# Import the data from 'credit.csv'
df = pd.read_csv('credit.csv')
df.head(5)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Approved  
0             1.0         Urban             Y  
1             1.0         Rural             N  
2             1.0         Urban             Y  
3             1.0         Urban             Y  
4             1.0         Urban             Y

In [7]:
# check the number of rows and observations
df.shape

(614, 13)

In [9]:
# How many application were approved and how many were denied?
df['Loan_Approved'].value_counts().plot.bar()

<Axes: xlabel='Loan_Approved'>

422 people (around 69%) out of 614 were approved for loan

### Missing value imputation

In [11]:
# check for missing values in each variable
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Approved         0
dtype: int64

Consider these methods to fill in the missing values:
* For numerical variables: imputate using mean or median
* For categorical variables: imputate using mode

For e.g.
In the `Loan_Amount_Term` variable, the value of 360 is repeating the most.

You can check that by using `train['Loan_Amount_Term'].value_counts()`

So you will replace the missing values in this variable using the mode of this variable. i.e. 360



For the `LoanAmount` variable, check if the variable has ouliers by plotting a box plot. If there are outliers use the median to fill the null values since mean is highly affected by the presence of outliers. If there are no outliers use mean to impute missing values in `LoanAmount'

In [7]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Approved         object
dtype: object

In [13]:
df['Gender'].value_counts()

Gender
Male      489
Female    112
Name: count, dtype: int64

In [15]:
df['Gender'].mode()[0]

'Male'

In [17]:
sns.distplot(df['LoanAmount'])

<Axes: xlabel='LoanAmount', ylabel='Density'>

In [19]:
# convert columns to object type
df['Credit_History'] = df['Credit_History'].astype('object')
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].astype('object')

In [21]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term      object
Credit_History        object
Property_Area         object
Loan_Approved         object
dtype: object

In [23]:
df['Married'].mode()[0]

'Yes'

In [25]:
# impute all missing values in all the features
#Categorical variables
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Married'].fillna(df['Married'].mode()[0], inplace=True)
df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)
df['Self_Employed'].fillna(df['Self_Employed'].mode()[0], inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0], inplace=True)
df['Credit_History'].fillna(df['Credit_History'].mode()[0], inplace=True)

#Numerical variable
df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)


In [27]:
# Confirm if there are any missing values left
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Approved        0
dtype: int64

### Data Prep

In [29]:
# drop 'Loan_ID' variable from the data. We won't need it.
df = df.drop('Loan_ID', axis=1)

In [31]:
df.head(3)

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
0   Male      No          0  Graduate            No             5849   
1   Male     Yes          1  Graduate            No             4583   
2   Male     Yes          0  Graduate           Yes             3000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       128.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   

  Property_Area Loan_Approved  
0         Urban             Y  
1         Rural             N  
2         Urban             Y

In [33]:
df.dtypes

Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Approved         object
dtype: object

In [35]:
raw = df.copy()

In [37]:
df.describe(include='all')

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
count     614     614        614       614           614       614.000000   
unique      2       2          4         2             2              NaN   
top      Male     Yes          0  Graduate            No              NaN   
freq      502     401        360       480           532              NaN   
mean      NaN     NaN        NaN       NaN           NaN      5403.459283   
std       NaN     NaN        NaN       NaN           NaN      6109.041673   
min       NaN     NaN        NaN       NaN           NaN       150.000000   
25%       NaN     NaN        NaN       NaN           NaN      2877.500000   
50%       NaN     NaN        NaN       NaN           NaN      3812.500000   
75%       NaN     NaN        NaN       NaN           NaN      5795.000000   
max       NaN     NaN        NaN       NaN           NaN     81000.000000   

        CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
count          614.000000  614.000000        614.000000      614.000000   
unique                NaN         NaN               NaN             NaN   
top                   NaN         NaN               NaN             NaN   
freq                  NaN         NaN               NaN             NaN   
mean          1621.245798  145.752443        342.410423        0.855049   
std           2926.248369   84.107233         64.428629        0.352339   
min              0.000000    9.000000         12.000000        0.000000   
25%              0.000000  100.250000        360.000000        1.000000   
50%           1188.500000  128.000000        360.000000        1.000000   
75%           2297.250000  164.750000        360.000000        1.000000   
max          41667.000000  700.000000        480.000000        1.000000   

       Property_Area Loan_Approved  
count            614           614  
unique             3             2  
top        Semiurban             Y  
freq             233           422  
mean             NaN           NaN  
std              NaN           NaN  
min              NaN           NaN  
25%              NaN           NaN  
50%              NaN           NaN  
75%              NaN           NaN  
max              NaN           NaN

In [39]:
df.head(2)

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
0   Male      No          0  Graduate            No             5849   
1   Male     Yes          1  Graduate            No             4583   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       128.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   

  Property_Area Loan_Approved  
0         Urban             Y  
1         Rural             N

In [41]:
# Create dummy variables for all 'object' type variables except 'Loan_Status'
df = pd.get_dummies(df, columns=['Gender', 'Married', 'Dependents','Education','Self_Employed','Property_Area'], dtype=int, drop_first=True)
df.head(2)

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0       128.0             360.0   
1             4583             1508.0       128.0             360.0   

   Credit_History Loan_Approved  Gender_Male  Married_Yes  Dependents_1  \
0             1.0             Y            1            0             0   
1             1.0             N            1            1             1   

   Dependents_2  Dependents_3+  Education_Not Graduate  Self_Employed_Yes  \
0             0              0                       0                  0   
1             0              0                       0                  0   

   Property_Area_Semiurban  Property_Area_Urban  
0                        0                    1  
1                        0                    0

In [43]:
# replace values in Loan_approved column
df['Loan_Approved'] = df['Loan_Approved'].replace({'Y':1, 'N':0})
df.head(2)

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0       128.0             360.0   
1             4583             1508.0       128.0             360.0   

   Credit_History  Loan_Approved  Gender_Male  Married_Yes  Dependents_1  \
0             1.0              1            1            0             0   
1             1.0              0            1            1             1   

   Dependents_2  Dependents_3+  Education_Not Graduate  Self_Employed_Yes  \
0             0              0                       0                  0   
1             0              0                       0                  0   

   Property_Area_Semiurban  Property_Area_Urban  
0                        0                    1  
1                        0                    0

In [45]:
# saving this procewssed dataset
df.to_csv('Processed_Credit_Dataset.csv', index=None)

### Data Partition

In [61]:
# Seperate the input features and target variable
x = df.drop('Loan_Approved',axis=1)
y = df.Loan_Approved

In [63]:
# splitting the data in training and testing set
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2, stratify=y)

In [65]:
x.shape

(614, 14)

In [53]:
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((491, 14), (123, 14), (491,), (123,))

In [97]:
# scale the data using min-max scalar
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler()

In [99]:
xtrain.head(2)

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
562             5923             2054.0       211.0             360.0   
326             4917                0.0       130.0             360.0   

     Credit_History  Gender_Male  Married_Yes  Dependents_1  Dependents_2  \
562             1.0            1            1             0             0   
326             0.0            1            0             0             0   

     Dependents_3+  Education_Not Graduate  Self_Employed_Yes  \
562              0                       0                  0   
326              0                       0                  0   

     Property_Area_Semiurban  Property_Area_Urban  
562                        0                    0  
326                        0                    0

In [101]:
# Fit-transform on train data
xtrain_scaled = scale.fit_transform(xtrain)
xtest_scaled = scale.transform(xtest)

In [103]:
xtrain_scaled

array([[0.06568353, 0.06070278, 0.29232996, ..., 0.        , 0.        ,
        0.        ],
       [0.05316408, 0.        , 0.17510854, ..., 0.        , 0.        ,
        0.        ],
       [0.03021592, 0.23956024, 0.276411  , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.02839898, 0.07107604, 0.14761216, ..., 0.        , 1.        ,
        0.        ],
       [0.09567544, 0.        , 0.39218524, ..., 0.        , 1.        ,
        0.        ],
       [0.04941821, 0.        , 0.18089725, ..., 0.        , 0.        ,
        1.        ]])

# **Models**

## <font color='chocolate'>**1. Logistic Regression**</font>

In [105]:
from sklearn.linear_model import LogisticRegression

lrmodel = LogisticRegression().fit(xtrain_scaled, ytrain)

In [107]:
# Predict the loan eligibility on testing set and calculate its accuracy.
# First, from sklearn.metrics import accuracy_score and confusion_matrix
from sklearn.metrics import accuracy_score, confusion_matrix

ypred = lrmodel.predict(xtest_scaled)

accuracy_score(ypred, ytest)

0.8048780487804879

In [109]:
ypred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1], dtype=int64)

In [111]:
ytest

281    1
27     1
255    1
402    1
217    1
      ..
18     0
341    0
452    0
21     1
422    1
Name: Loan_Approved, Length: 123, dtype: int64

In [113]:
# Print the confusion matrix
confusion_matrix(ytest, ypred)

array([[14, 24],
       [ 0, 85]], dtype=int64)

In [115]:
# to check how probabilities are assigned
pypred = lrmodel.predict_proba(xtest_scaled)

In [129]:
pypred

array([[0.10992068, 0.89007932],
       [0.2170895 , 0.7829105 ],
       [0.3557264 , 0.6442736 ],
       [0.2338797 , 0.7661203 ],
       [0.11308529, 0.88691471],
       [0.27039163, 0.72960837],
       [0.28995865, 0.71004135],
       [0.18201351, 0.81798649],
       [0.20462495, 0.79537505],
       [0.19971565, 0.80028435],
       [0.19551604, 0.80448396],
       [0.37740449, 0.62259551],
       [0.20924686, 0.79075314],
       [0.25794846, 0.74205154],
       [0.2797237 , 0.7202763 ],
       [0.21291314, 0.78708686],
       [0.19924428, 0.80075572],
       [0.18062829, 0.81937171],
       [0.13904643, 0.86095357],
       [0.11164205, 0.88835795],
       [0.15839075, 0.84160925],
       [0.48524861, 0.51475139],
       [0.19900769, 0.80099231],
       [0.17881513, 0.82118487],
       [0.12540605, 0.87459395],
       [0.19919489, 0.80080511],
       [0.18501595, 0.81498405],
       [0.0821981 , 0.9178019 ],
       [0.11710328, 0.88289672],
       [0.18725613, 0.81274387],
       [0.

In [139]:
# to change the default threshold and to make it 70% and above
proba_pred = (pypred[:, 1] >= 0.8).astype(int)

In [141]:
accuracy_score(proba_pred, ytest)

0.6504065040650406

In [143]:
from sklearn.metrics import precision_score
precision_score(proba_pred,ytest)

0.6

## <font color='chocolate'>**2. Random Forest**

In [145]:
# Import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

In [147]:
# Let's list the tunable hyperparameters for Random Forest algorithm
RandomForestClassifier().get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

For random forests,

* The first hyperparameter to tune is n_estimators. We will try 100 and 200.

* The second one is max_features. Let's try - 'auto', 'sqrt', and 0.33.

* The third one is Max_depth. Let's try - 3, 4

In [73]:
xtrain.shape

(491, 20)

### Hyperparameter Tuning

In [151]:
rfmodel = RandomForestClassifier(n_estimators=2,
                                 max_depth=2,
                                 max_features=10)
rfmodel.fit(xtrain, ytrain)

# predict on xtest
ypred = rfmodel.predict(xtrain)

from sklearn.metrics import accuracy_score, confusion_matrix

print(accuracy_score(ypred, ytrain),'\n')
print(confusion_matrix(ytrain, ypred))

0.814663951120163 

[[ 70  84]
 [  7 330]]


In [153]:
ypred = rfmodel.predict(xtest)

from sklearn.metrics import accuracy_score, confusion_matrix

print(accuracy_score(ypred, ytest),'\n')
print(confusion_matrix(ytest, ypred))

0.8048780487804879 

[[15 23]
 [ 1 84]]


In [155]:
# plot a feature importance chart
rfmodel.feature_importances_

array([0.04229889, 0.02001629, 0.05491021, 0.        , 0.88277461,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

## Cross Validation

In [ ]:
# import rquired libraries
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

# if you have a imbalanced dataset, you can use stratifiedKFold
from sklearn.model_selection import StratifiedKFold

### For Logistic Regression

In [ ]:
# Set up a KFold cross-validation
kfold = KFold(n_splits=5)

# Use cross-validation to evaluate the model
lr_scores = cross_val_score(lrmodel, xtrain_scaled, ytrain, cv=kfold)

# Print the accuracy scores for each fold
print("Accuracy scores:", lr_scores)

# Print the mean accuracy and standard deviation of the model
print("Mean accuracy:", lr_scores.mean())
print("Standard deviation:", lr_scores.std())


Accuracy scores: [0.7979798  0.81632653 0.81632653 0.81632653 0.83673469]
Mean accuracy: 0.8167388167388168
Standard deviation: 0.012265772106957356


### For Random Forest

In [ ]:
# Set up a KFold cross-validation
kfold = KFold(n_splits=5)

# Use cross-validation to evaluate the model
rf_scores = cross_val_score(rfmodel, xtrain_scaled, ytrain, cv=kfold)

# Print the accuracy scores for each fold
print("Accuracy scores:", rf_scores)

# Print the mean accuracy and standard deviation of the model
print("Mean accuracy:", rf_scores.mean())
print("Standard deviation:", rf_scores.std())


Accuracy scores: [0.7979798  0.81632653 0.81632653 0.81632653 0.83673469]
Mean accuracy: 0.8167388167388168
Standard deviation: 0.012265772106957356


### Note:

1. By using cross-validation, we can get a better estimate of the performance of the model than by using a single train-test split. This is because cross-validation uses all the data for training and testing, and averages the results over multiple iterations, which helps to reduce the impact of random variations in the data.
<br><br>
2. **StratifiedKFold** is a variation of KFold that preserves the proportion of samples for each class in each fold. This is important when the target variable is imbalanced, i.e., when some classes have many more samples than others. By preserving the class proportions in each fold, StratifiedKFold ensures that each fold is representative of the overall dataset and helps to avoid overfitting or underfitting on specific classes.